### ISSUE TITLE
Decide where to add lectures in the Rails curriculum

### ISSUE THREAD

**Issue by gabebw** [railsbridge-boston/docs#26]
The original RB docs have this at the bottom of a lot of pages:

```
Next Step

Wait for the next lecture!

(…is the lecture over? Go to the next section)
```

I think that's great because it lets students know that there's a lecture coming up and lets them know not to proceed. We should decide where we're having lectures and put that text at the bottom of the appropriate lessons.

I think we should have a lecture on "What is a Model" right before people create migrations.

**Comment by mxie** [comment]
Sorry for the delay!

In the past, we've had lectures with the following titles coming before these particular pages:

Lecture Title | Old Section Title | New Section Title
--------------- | --------------- | ---------------
Intro to Ruby | Intro/The Ruby Language | Intro to Rails/Ruby Language
Starting a Rails Application | Creating a Rails Application | Running Your Application Locally
Models, Scaffolding, and Migrations | Creating and Running a Database Migration | Creating a Migration
Exploring Model-View-Controller | Voting on Topics | same
Rails Navigation, Links, and Routes | Setting the Default Page |  N/A or maybe part of Allow People to Vote
