### ISSUE TITLE
Use msysgit for all windows versions

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/docs#45]
We already recommend the msysgit build for Windows machines that are too old to install .NET in order to install the GitHub client (has a big confusing UI that prompts you to sign up for a GitHub account). I think it could be a simpler way to get SSH installed and on the student's PATH.

http://guides.beanstalkapp.com/version-control/git-on-windows.html

Need to run through the install on a Windows machine and see where the "Adjusting your Path environment" bit is. This is the important part; otherwise a command prompt won't have PATH set up. (I think this is what led some TAs to try installing Cygwin which IMHO is a bad idea.)

I haven't tried this, but if "Git Bash" doesn't change the startup directory, it would be much better than the GitHub-branded "Git Shell", which changes the startup dir from the user's home dir to something in a GitHub-specific documents directory. The context menu could also be really useful for starting the shell.

**Comment by eudaimonious** [comment]
Agreed. Going to open a PR to update to Git Bash.

**Comment by eudaimonious** [comment]
https://github.com/railsbridge-boston/docs/pull/52
