### ISSUE TITLE
Easier folder creation and getting to Vagrant steps

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/docs#46]
The VM setup steps kind of dump a lot of command line stuff on you at once, assuming you already created the folder (no student I started walking through it had) and understand what cding to it is. I think we should start like this instead:
1. Install all the software.
   1a. Additional step for Mac users: find Terminal and drag it to your Dock.
2. Create a folder in Finder or Explorer, however you are comfortable doing it, and wherever you like to keep things organized. We can suggest "railsbridge" on the student's desktop if they have no preference. If they have a previous-workshop folder, create a new folder.
   3a. On a Mac, **drag the railsbridge folder onto Terminal in the Dock.**
   3b. On Windows, using msysgit as described in #45, right-click the folder and click "Git Bash".

Now your terminal is open and already in the right directory to start running Vagrant. We don't have force students to know the local pathname or use cd just to get into the VM (this is one of those things that's totally arcane but we're used to it because we use cd all the time).

Need to try this out on a real Windows machine to see if it works in practice as well as in theory, and then rewrite a lot of instructions. First, though, how do people feel about the general idea?

Note that this means not necessarily calling the folder `workspace`, so we should retire the symlink inside the VM and have their `.bashrc` cd to `/vagrant` for them, rather than hiding that behind a layer of indirection.

**Comment by gabebw** [comment]
Oooh, I love dragging the folder to the terminal, that's easy AND intuitive! Retiring workspace is also probably a good idea - it gives them some control over something totally new, which might help them feel more comfortable with the setup.

**Comment by pcai** [comment]
please see #63
