### ISSUE TITLE
The about page is broken...

### ISSUE THREAD

**Issue by jacindaz** [railsbridge-boston/docs#58]

**Comment by gabebw** [comment]
Hi, thanks for reporting this!

Which URL are you trying to access?

It looks like http://www.railsbridgeboston.org/pages/about is working for me, but maybe you're looking at something else?

**Comment by jacindaz** [comment]
I believe I was looking at /about, which I think I go to via the nav bar. Though right now, I can't load railsbridgeboston.org at all, I got a 400:

400 Bad Request
nginx

I'll try again in a few hours, I definitely could load the homepage and the /pages/resources yesterday evening...

**Comment by bcarreno** [comment]
```
$ curl -I http://railsbridgeboston.org/
HTTP/1.1 400 Bad Request
Server: nginx/1.0.15
Date: Mon, 21 Sep 2015 16:58:34 GMT
Content-Type: text/html
Connection: keep-alive
Keep-Alive: timeout=15
Content-Length: 166

$ curl -I http://www.railsbridgeboston.org/
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
Date: Mon, 21 Sep 2015 16:59:29 GMT
Status: 200 OK
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Etag: W/"d5db1e6202dd1faebd99592eda88336a"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _railsbridgeboston_dot_org_session=cXhQRE51cGZpZ0w5RU9RaFhtcG95YXJuakwvV2ZuRkpVTkIzd1pOQktTb2IyUk0yejJkTTYzd0RUdzBZQUdsbW14Tmo4RmJzNmZJTEpKaG1obUpUYmRCT2Vtc2pnNTNTQmxSbDRsZ3F6akM5WHVTSExNRDAwZjhHUTU3TUF5ck5sOThnS3BWUDg1MFRhL2tEVjArOTRRPT0tLUMrakZQZWdLem5aSW1JY1lENEVDQ2c9PQ%3D%3D--4c1c34ec1acbdf1b514fdee414087c3dfd475fae; path=/; HttpOnly
X-Request-Id: de1c9028-0b65-408d-b8e4-c43bebf16a8a
X-Runtime: 0.386829
Via: 1.1 vegur
```

**Comment by gabebw** [comment]
I think Braulio's point is that www.railsbridgeboston.org (with the WWW) works, but railsbridgeboston.org (no WWW) doesn't.

**Comment by jacindaz** [comment]
Ah, ok, yes. With the www it works, without it doesn't. 

This page is still broken: 
http://www.railsbridgeboston.org/about.html

I get to that page when scrolling all the way down on the homepage, and clicking on "Learn more about us".

**Comment by gabebw** [comment]
> I get to that page when scrolling all the way down on the homepage, and clicking on "Learn more about us".

Aha, that narrows it down for me, thanks!

I fixed it here: https://github.com/railsbridge-boston/railsbridgeboston_dot_org/commit/b48f280825cdfcbb90d9f7acfa3ec80cbcee1987

And the link should work for you now on http://www.railsbridgeboston.org/
