### ISSUE TITLE
Mega-issue for June Workshop preparation

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/docs#63]
The planning meeting for June is tonight and I might not be able to make it, so I want to put some thoughts down about what definitely needs to be addressed. I'd like to set the end of May as a hard deadline for having these prepared so that they don't slip until just before the workshop.
- Instructions for copying files from USBs: these need to be updated to reflect the directory layout produced by https://github.com/railsbridge-boston/spoon-builder. That is, students will need to copy _two_ directories: one for the VM (same for all students), and one for their particular operating system (different for Win/Mac/Linux). (The latter can be deleted on students laptops after programs are installed, but maybe the former can be reused as the working directory?)
- The `workspace` directory: it's time to move on from this, finally. The VM should be updated to cd to `/vagrant`. The instructions, I think, should have students create the folder they're going to work in on their desktop. From my experience at the last workshop it looks like Windows 8 and up consistently opens up a shell in the user's home directory and the desktop is a subdirectory `Desktop` of that -- same as OS X.
- The which-interface-does-`rails server`-listen-on problem: I proposed using an application template for this (using a config setting proposed by a guy whose name I don't remember from the 2016-04 workshop), it seemed to work, and no one has reported it not working. Therefore I think we should merge it into the VM and update the instructions to (1) add the template option to `rails new` (2) remove all usage of `-b 0.0.0.0` every time students start the server.

If these can all be turned around really fast we can look at rebasing/rewriting the docs on upstream, but that may not be realistic to do in <1month.

Anything else with limited scope that should absolutely be done before June, please add in a comment.

**Comment by decklin** [comment]
I am starting on both the copy updates (we're going to have students copy a `railsbridge` directory), but will want someone to review.

We're not sure if we want to do the app template idea (https://github.com/railsbridge-boston/railsbridge-vm/issues/20). Do other organizers have opinions?

When it gets closer to the end of the month I'll tag a VM release candidate and ping @SherrySeibel to build it.

**Comment by pcai** [comment]
closing this out for now since the curriculum is being rewritten for codespaces, and for a local installation i would advocate for docker desktop + containers
