### ISSUE TITLE
Update virtualbox and vagrant versions?

### ISSUE THREAD

**Issue by kookster** [railsbridge-boston/docs#66]
I see older versions intentionally kept for older windows installs, but there are updated versions of virtualbox (5.0 instead of 4.5) and vagrant (1.8.4 instead of 1.8.1) avaiable

**Comment by decklin** [comment]
We want to keep VirtualBox in step with the version of the guest additions in Ubuntu, and we're currently on Ubuntu 14.04, which ships 4.3. I don't know for sure off the top of my head but I think 16.04 (now released) should include 5.0. We can probably do this update before the September workshop.

If Ubuntu LTS releases (at some point leading up to 18.04) start lagging to a point where the matching series of VirtualBox is no longer receiving security updates, then we'll want to revisit this. But for now I think we're fine.
