### ISSUE TITLE
Warn that creating a new rails app may take a while

### ISSUE THREAD

**Issue by edwardloveall** [railsbridge-boston/docs#74]
Creating a Rails Application [Step 2](http://docs.railsbridgeboston.org/intro-to-rails/creating_a_rails_application#step2) asks you to create a rails app with `rails new`. Step 3 asks you to cd into the directory, but most likely the app isn't done being bundled yet so `cd suggestotron` won't do much. Possible area for student confusion.

**Comment by pcai** [comment]
Added a note in the latest branch we're working on:

![image](https://github.com/railsbridge-boston/docs/assets/222655/74c56ded-a2a2-480b-bbbf-c17c4f0df80e)
