### ISSUE TITLE
Suggested text editor...

### ISSUE THREAD

**Issue by llawrenc** [railsbridge-boston/docs#81]
Hi, I just wanted to suggest a replacement for Sublime Text, since it has a cost associated with it...Both the Git Atom editor and the Adobe Brackets editors look very comprehensive and capable, and best of all there is no cost for either.  I found Brackets more compatible than Atom, and it has been fantastic.

**Comment by BrianBorge** [comment]
Another great and free option is [Visual Studio Code](https://code.visualstudio.com/)

**Comment by pcai** [comment]
Thanks. We're updating the curriculum to use github codespaces so we'll naturally be using vscode online. Closing this out for now
