### ISSUE TITLE
Feedback on Installfest instructions for Windows 10

### ISSUE THREAD

**Issue by mxie** [railsbridge-boston/docs#87]
Someone had emailed me with some feedback on the Installfest instructions:

> Running Windows 10 Home edition, 64-bit. 
> 
> I ran the installers as shown, in the order specified.  
> Everything worked fine in the end.  Since Installfest instructions did not specify some of the installer defaults or checkbox options explicitly, I made notes below anyplace I made a guess or just wondered whether I was doing it right.  The thing that stood out was that other programs want to install Git after I had already installed it, so I had to uncheck that option.  
> 
> VirtualBox 5.0 
>     > accepted 'register file associations' already checked 
> 
> Jan 2017 VM Image 
> 
> Vagrant 1.9 
> 
> Sublime Text 2
> 
> Git for Windows
>     > PATH environment: defaulted to 'use git from the windows command prompt,' not from bash 
>     > line endings: 'checkout windows style, commit unix-style line endings' 
>     > terminal emulator: use MinTTY (not cmd.exe) 
>     > extra options: did not enable symbolic links 
> 
> RailsInstaller for v 2.3 /includes RubyInstaller + tools
>     > unchecked 'install Git' (Git already installed) 
>     > manually added username/email/ssh configs in Git as RailsInstaller had not done so 
> 
> Heroku CLI 
>     > unchecked option to install Git, since a newer version of Git is already installed  
>     > login and adding ssh key was completed via cmd.exe, because in Windows this action was not supported in Git bash

**Comment by pcai** [comment]
closing this as stale since our next iteration is on codespaces -- or alternatively, I would advocate for VSC with containers
